### ISSUE TITLE
Api selalu ofline

### ISSUE THREAD

**Issue by runforreksi** [showcheap/tagihan-pln#1]
gan kenapa ofline mulu ya lagi ngerjain skripsi bingung cari apinya
kalau boleh minta app apinya langsung
ke gmail aja gan 
reksiiyau@gmail.com

**Comment by suciptoid** [comment]
API nya sudah ditutup oleh PLN gan

**Comment by runforreksi** [comment]
bos ada ngak selain yang lama

**Comment by otpicus** [comment]
Silahkan berkerjasama dengan pihak PPOB biasanya mereka punya akses untuk chek tagihan.
